spring:
  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/infor
    username: root
    password: admin
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
  thymeleaf:
    cache: false
  aop:
    auto: true  #启动aop配置
server:
  port: 8080
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #配置sql语句在控制台输出
pagehelper:
  reasonable: true
  helper-dialect: mysql

